# -*- coding: utf-8 -*-
"""Untitled31.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zrgu04taVIWofR-iKwA-5ZiBaXwDIxN1
"""

import streamlit as st
import pandas as pd
import plotly.express as px

# Load the healthcare data
data = {
    'age': [67, 61, 80, 49, 79, 81, 74, 69, 59, 78],
    'avg_glucose_level': [228.69, 202.21, 105.92, 171.23, 174.12, 186.21, 70.09, 94.39, 76.15, 58.57],
    'bmi': [36.6, None, 32.5, 34.4, 24.0, 29.0, 27.4, 22.8, None, 24.2],
    'hypertension': [0, 0, 0, 0, 1, 0, 1, 0, 0, 0],
    'stroke': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
}
df = pd.DataFrame(data)

# Streamlit app title
st.title("Healthcare Data Visualization")

# 3D Scatter Plot
st.subheader("3D Scatter Plot of Age, Glucose Level, and BMI")
fig_3d = px.scatter_3d(df, x='age', y='avg_glucose_level', z='bmi', color='stroke',
                        title='3D Scatter Plot of Age, Glucose Level, and BMI',
                        labels={'age': 'Age', 'avg_glucose_level': 'Average Glucose Level', 'bmi': 'BMI'},
                        color_discrete_map={0: 'blue', 1: 'red'})
st.plotly_chart(fig_3d)

# Contour Plot
st.subheader("Contour Plot of Age vs. Average Glucose Level")
fig_contour = px.density_contour(df, x='age', y='avg_glucose_level', color='stroke',
                                 title='Contour Plot of Age vs. Average Glucose Level',
                                 labels={'age': 'Age', 'avg_glucose_level': 'Average Glucose Level'},
                                 color_discrete_map={0: 'blue', 1: 'red'})
st.plotly_chart(fig_contour)

# Scatterplot Matrix
st.subheader("Scatterplot Matrix")
numerical_columns = ['age', 'avg_glucose_level', 'bmi']
fig_scatter_matrix = px.scatter_matrix(df, dimensions=numerical_columns, color='hypertension',
                                       title='Scatterplot Matrix Hypertension for Hypertension',
                                       labels={col: col for col in numerical_columns})
st.plotly_chart(fig_scatter_matrix)

# Sunburst Chart
st.subheader("Sunburst Chart: Relationship between Smoking Status, Gender, and Stroke")
data_sunburst = {
    'smoking_status': ['formerly smoked', 'never smoked', 'never smoked', 'smokes', 'never smoked',
                       'formerly smoked', 'never smoked', 'Unknown', 'Unknown', 'formerly smoked'],
    'gender': ['Male', 'Female', 'Male', 'Female', 'Female', 'Male', 'Male', 'Female', 'Female', 'Female'],
    'stroke': [1, 1, 0, 1, 0, 1, 0, 1, 0, 1]
}
df_sunburst = pd.DataFrame(data_sunburst)
fig_sunburst = px.sunburst(df_sunburst, path=['smoking_status', 'gender'], values='stroke',
                           title='Sunburst Chart: Relationship between Smoking Status, Gender, and Stroke',
                           color_continuous_scale='Viridis',
                           labels={'smoking_status': 'Smoking Status', 'gender': 'Gender', 'stroke': 'Stroke'})
st.plotly_chart(fig_sunburst)

# Animated Bar Chart
st.subheader("Animated Bar Chart: Strokes Over Age")
data_bar = {
    'age': [30, 35, 40, 45, 50, 55, 60, 65, 70, 75],
    'stroke': [0, 0, 1, 0, 1, 0, 1, 0, 1, 0]
}
df_bar = pd.DataFrame(data_bar)
fig_bar = px.bar(df_bar, x='age', y='stroke', title='Animated Bar Chart: Strokes Over Age',
                  labels={'age': 'Age', 'stroke': 'Stroke'},
                  animation_frame='age',
                  range_x=[30, 75],
                  range_y=[0, 1],
                  color='stroke',
                  color_discrete_map={0: 'blue', 1: 'red'},
                  text='stroke')
st.plotly_chart(fig_bar)